### ISSUE TITLE
GROUP RUBY CAPSTONE PROJECT

### ISSUE THREAD

**Issue by AnsarIbrahim** [AnsarIbrahim/CatalogMyThings#35]
# This PR Contains:

## We are two members in this group 2️⃣

- [Md. Porag Sarkar](https://github.com/porag-m06) is team member 1 and was assigned a task list for team member 1
- [Ansar Ibrahim](https://github.com/AnsarIbrahim) is team member 2 and was assigned a task list for team member 2

**Comment by omar-muhamad** [comment]
# Changes Required ♻️
### Hi @AnsarIbrahim and @porag-m06,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Changes Required) Aspects to improve: ♻️

- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#:~:text=Has%20a%20descriptive%20title.), Please add a descriptive title for all group tasks that you created, for example, the `group task 1` suppose to be named `Create Item class`.

![image](https://github.com/AnsarIbrahim/My_Things-Ruby-Capstone/assets/68796232/d9290618-00e1-45a2-8759-f28fb421033b)

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by AnsarIbrahim** [comment]
# I have implemented the revisions suggested by the reviewer.

**Comment by LionRouge1** [comment]
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Highlights
- Great job, implementing the requested changes :+1:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
